### ISSUE TITLE
Discord login loop

### ISSUE THREAD

**Issue by CRAKD** [zet4/disguard#4]
I have it all setup it redirects me to discord to authorize the app when you click authorize you get redirected again to authorize again. Never seems to accept the token. If you hit cancel instead of authorize you do get the 404 nothing to see here screen.

**Comment by roundaboutluke** [comment]
You cannot use Disguard at domain.com as upon authorisation it kicks back to domain.com which will cause the login loops you are experiencing - this is likely your issue.

Edit: Got some guidance from zet4 and will be looking to try and implement this into the config soon and submitting a PR.

**Comment by roundaboutluke** [comment]
I had to put my plans on hold due to RL, but here's a workaround easier than that anyway! (when using Nginx though would be possible with apache, assuming a full working setup with the login loop as described. Disguard hosted on port 3000 though will work on whatever just change it as such)

Simply add two locations to your server block -

    location /login/ {
       proxy_pass http://127.0.0.1:3000/;
    }

    location /oauth {
       proxy_pass http://127.0.0.1:3000;
    }


change your **config.yaml** settings to reflect this

`redirect_url: "https://yourdomain.com/login/oauth/callback`

Finally add that to your Discord API apps Redirect URI(S)

**Redirect URI(s)**
`https://yourdomain.com/login/oauth/callback` and `http://yourdomain.com/login/oauth/callback`

Issue solved! And if you for some reason already use /login/ for something else simply subsititute it for any other /word/ you like, making sure to change the location, config.yaml and redirect URI(s) to reflect this.

**Comment by zet4** [comment]
Closed due to inactivity and old age.
